---

- name: Deploy web servers on VM1 and VM2
  hosts: webservers
  #remote_user: ec2-user
  become: yes
  tasks:
  #- name: Set ssh port to 8080
   # set_fact:
    #      ansible_port: 8080
  - name: Ensure httpd is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: Ensure httpd is running on VM2 and VM3
    service:
          name: httpd
          enabled: true
          state: started
  - name: Print Hello world from SJSU on VM2 and VM3 web server(/var/www/html/index.html)
    copy:
       dest: /var/www/html/index.html
       content:
               "Hello World from SJSU"